# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_XDs6mYLACkaN_zA3ehF1fhgY3wuREXK
"""

pip install opencv-python

from google.colab.patches import cv2_imshow
import cv2
picture1=cv2.imread("rasm.jpg")
picture2=cv2.imread("RASM1.jpg")
picture3=cv2.imread("rasm2.jpg")
picture4=cv2.imread("rasm3.jpg")
picture5=cv2.imread("rasm4.jpg")
cv2_imshow(picture1)
cv2_imshow(picture2)
cv2_imshow(picture3)
cv2_imshow(picture4)
cv2_imshow(picture5)

color1=cv2.cvtColor(picture1,cv2.COLOR_BGR2GRAY)
cv2_imshow(color1)
color2=cv2.cvtColor(picture2,cv2.COLOR_BGR2GRAY)
cv2_imshow(color2)
color3=cv2.cvtColor(picture3,cv2.COLOR_BGR2GRAY)
cv2_imshow(color3)
color4=cv2.cvtColor(picture4,cv2.COLOR_BGR2GRAY)
cv2_imshow(color4)
color5=cv2.cvtColor(picture5,cv2.COLOR_BGR2GRAY)
cv2_imshow(color5)